version: 1.0.{build}
image:
- Visual Studio 2017
# Required for kudu deployment (msbuild 14) to Azure
- Visual Studio 2015
- Visual Studio 2019
before_build:
- ps: nuget restore
build:
  verbosity: minimal
